# Account Operations
ACCOUNT_LOGIN_SUCCESS = 100
ACCOUNT_LOGIN_FAIL = 101
ACCOUNT_LOGIN_EMAIL_INVALID = 102
ACCOUNT_LOGIN_PASSWORD_INVALID = 103

ACCOUNT_REGISTER_SUCCESS = 105
ACCOUNT_REGISTER_EMAIL_INVALID = 106
ACCOUNT_REGISTER_PASSWORD_INVALID = 107
ACCOUNT_REGISTER_ERROR = 108

ACCOUNT_UPDATE_PASSWORD_INVALID = 109
ACCOUNT_UPDATE_EMAIL_INVALID = 110
ACCOUNT_UPDATE_SUCCESS = 111
ACCOUNT_UPDATE_FAIL = 112

ACCOUNT_LOGOUT_SUCCESS = 115
ACCOUNT_TOKEN_ERROR = 120
ACCOUNT_GET_SUCCESS = 125

ACCOUNT_USERNAME_NOT_EXIST = 126
ACCOUNT_USERNAME_EXIST = 127